name: domain
description: "Domain Module"
version: 0.0.1

environment:
  sdk: 3.9.2
  flutter: 3.35.3

resolution: workspace
dependencies:
  flutter:
    sdk: flutter

  equatable:
  injectable:
  freezed_annotation:

dev_dependencies:
  build_runner:
  freezed:
  injectable_generator: